exports.getRestaurant = () =>
{
  var restaurantsArray = [
    "Applebee's",
    "Arby's",
    "Atlanta Bread Company",
    "Auntie Anne's",
    "A&W",
    "Back Yard Burgers",
    "Baja Fresh",
    "Benihana",
    "Bennigan's",
    "Bj's Restaurants",
    "Blaze Pizza",
    "Blimpie",
    "Bob Evans Restaurant",
    "Bojangles",
    "Bonefish Grill",
    "Boston Market",
    "Buffalo Wild Wings",
    "BurgerFi",
    "Burger King",
    "California Pizza Kitchen",
    "Captain D's",
    "Carl's Jr / Hardee's",
    "Carrabba's Italian Grill",
    "Charleys Philly Steaks",
    "Checkers / Rally's",
    "Cheddar's",
    "Chick-fil-A",
    "Chili's",
    "Chipotle",
    "Chuck E. Cheese's",
    "Church's Chicken",
    "Cicis",
    "Cook Out",
    'Cracker Barrel',
    "Culver's",
    "Dave & Busters",
    "Dairy Queen",
    "Del Taco",
    "Denny's",
    "Domino's Pizza",
    "Dunkin",
    "Einstein Bros. Bagels",
    "El Pollo Loco",
    "Fazoli's",
    "Firehouse Subs",
    "Freddy's Frozen Custard & Steakburgers",
    "Friendly's",
    "Five Guys",
    "Fogo de Chao",
    "Fox's Pizza Den",
    "Fuddruckers",
    "Golden Corral",
    "Hard Rock Cafe",
    "Hooters",
    "Houlihan's",
    "Huddle House",
    "Hungry Howie's Pizza",
    "Hwy 55 Burgers Shakes & Fries",
    "IHOP",
    "In-N-Out Burger",
    "Jack in the Box",
    "Jamba Juice",
    "Jason's Deli",
    "Jersey Mike's Subs",
    "Jet's Pizza",
    "Jimmy John's",
    "Joe's Crab Shack",
    "Johnny Rockets",
    "Jollibee",
    "KFC",
    "Krystal",
    "Little Caesars",
    "Logan's Roadhouse",
    "Long John Silver's",
    "Maggiano's Little Italy",
    "Marco's Pizza",
    "Marie Callender's",
    "McAlister's Deli",
    "McDonald's",
    "MOD Pizza",
    "Moe's Southwest Grill",
    "Newk's Eatery",
    "O'Charley's",
    "Old Country Buffet",
    "Olive Garden",
    "On the Border Mexican",
    "Outback Steakhouse",
    "Panda Express",
    "Panera Bread",
    "Papa John's Pizza",
    "Papa Murphy's",
    "Pappadeaux Seafood Kitchen",
    "Pei Wei Asian Diner",
    "P.F. Chang's",
    "Pita Pit",
    "Pizza Hut",
    "Planet Smoothie",
    "Pollo Campero",
    "Ponderosa / Bonanza Steakhouse",
    "Popeyes",
    "Potbelly Sandwich Works",
    "Qdoba",
    "Quiznos",
    "Raising Cane's Chicken Fingers",
    "Red Lobster",
    "Red Robin",
    "Romano's Macaroni Grill",
    "Ruby Tuesday",
    "Ruth's Chris Steak House",
    "Saladworks",
    "Sbarro",
    "Schlotzsky's",
    "Shake Shack",
    "Shakey's Pizza",
    "Shane's Rib Shack",
    "Shoney's",
    "Sizzler",
    "Smashburger",
    "Smoothie King",
    "Sonic Drive-In",
    "Starbucks",
    "Steak and Ale",
    "Steak 'n Shake",
    "Subway",
    "Sweetgreen",
    "Taco Bell",
    "Taco John's",
    "Taco Mac",
    "Taco Time",
    "Texas Roadhouse",
    "TGI Fridays",
    "The Capital Grille",
    "The Cheesecake Factory",
    "The Halal Guys",
    "The Habit Burger Grill",
    "The Melting Pot",
    "The Original Pancake House",
    "Tim Hortons",
    "Tropical Smoothie Cafe",
    "Twin Peaks",
    "Waffle House",
    "Wayback Burgers",
    "Wendy's",
    "Wetzel's Pretzels",
    "Whataburger",
    "Which Wich?",
    "White Castle",
    "Wienerschnitzel",
    "Wingstop",
    "WingStreet",
    "Zaxby's",
  ];
  return restaurantsArray;
};
